### ISSUE TITLE
Can't compute eigenvalues of Hermitian Diagonal matrix for generic types

### ISSUE THREAD

**Issue by araujoms** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#139]
As the title says, the following code fails:
```julia
using LinearAlgebra
using GenericLinearAlgebra
m = Hermitian(Diagonal(randn(BigFloat,2)))
eigvals(m)
```
This is not related to `BigFloat`, it also fails for `Double64` and `Float128`. I think the underlying issue is the same as #53564, the lack of a universal fallback.

To make life even stranger, after `GenericLinearAlgebra` is loaded this code starts failing even for `Float64`. That is,
```julia
using LinearAlgebra
m = Hermitian(Diagonal(randn(Float64,2)))
eigvals(m)
```
works fine, but
```julia
using LinearAlgebra
using GenericLinearAlgebra
m = Hermitian(Diagonal(randn(Float64,2)))
eigvals(m)
```
fails.

I had previously reported this issue under JuliaLang/julia#54412 under the misconception that `GenericLinearAlgebra` was a standard library, but @aravindh-krishnamoorthy noted that it isn't, and this issue is not caused by `LinearAlgebra`.

**Comment by andreasnoack** [comment]
It should be fixed by https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/140. Longer term, it would probably be good to avoid the piracy somehow. On the other hand, it's pretty useful (when it doesn't break LinearAlgebra).
