### ISSUE TITLE
Move to JuliaMath?

### ISSUE THREAD

**Issue by jiahao** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#16]

**Comment by ChrisRackauckas** [comment]
Yes. Never even knew this existed until a comment on ForwardDiff.

**Comment by dlfivefifty** [comment]
I just used this package for `BigFloat` quadrature rules, not sure how I found it.

Alternatively, maybe it's appropriate as part of StdLib/LinearAlgebra.jl, though that's a bigger task.

**Comment by mfalt** [comment]
This package seems like a really great step to getting more general functionality in many packages, what is the plan for moving and registering it so it can be used as a dependency?

**Comment by andreasnoack** [comment]
Yes. I'll just need to document it slightly better and also test a few things a little better.

**Comment by andreasnoack** [comment]
It's now registered and has moved to JuliaLinearAlgebra
