### ISSUE TITLE
Do you intend to tag this?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#40]
this (or thereabouts) gets `eigvals(::Matrix{DoubleFloat{Float64})` to work
```julia
using LinearAlgebra
import LinearAlgebra: rmul!, lmul!
include("juliaBLAS.jl")
include("householder.jl")
include("eigenGeneral.jl")
```

Should I copy those files into a GenericLinearAlgebra subdir and credit you and this repo?

**Comment by andreasnoack** [comment]
Yes. I have a few fixes I need to get in and then I'd also like to initiate the documentation. Then I'll register. Hopefully later this week.

**Comment by andreasnoack** [comment]
It took a little longer to get things into a reasonable shape.

Fixed by https://github.com/JuliaLang/METADATA.jl/pull/20088

**Comment by giordano** [comment]
This can be closed, then?

**Comment by andreasnoack** [comment]
The PR has now been merged so this can be closed.
