### ISSUE TITLE
Are there a Chordal sparse matrix function?

### ISSUE THREAD

**Issue by erikfilias** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#45]
I work in Convex Optimization, and I look for any function like a Python's Chordal Matrix Package.
Are there something like that in JuliaLang?

**Comment by simonbyrne** [comment]
I'm not sure. You would probably be better asking this question on http://discourse.julialang.org/.

**Comment by erikfilias** [comment]
> I'm not sure. You would probably be better asking this question on http://discourse.julialang.org/.

Thank you. I'll do it.

**Comment by samuelsonric** [comment]
@erikfilias There are three:

- CliqueTrees.jl
- ChordalGraph.jl
- Chordal.jl
