### ISSUE TITLE
juliaBLAS needs update (and tests)

### ISSUE THREAD

**Issue by dmbates** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#93]
The `juliaBLAS.jl` source file was last updated many years ago and LinearAlgebra.jl has been reorganized since.  There is some inconsistency in `juliaBLAS.jl` with names that are now in the `LinearAlgebra.BLAS` module.  For example, the qualified names `BLAS.ger!` and `BLAS.syr!` occur in lines 12 and 31 but unqualified names `syrk!` and `herk!` in lines 52 and 55

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/95
